insert into BuyBest (storeID, addr, state, zip) values (1, 'Sloan', 'Alabama', '36628');
insert into BuyBest (storeID, addr, state, zip) values (2, 'Florence', 'Arkansas', '72905');
insert into BuyBest (storeID, addr, state, zip) values (3, 'Melvin', 'Florida', '32405');
insert into BuyBest (storeID, addr, state, zip) values (4, 'Nevada', 'Louisiana', '70894');
insert into BuyBest (storeID, addr, state, zip) values (5, 'David', 'Kansas', '66286');
insert into BuyBest (storeID, addr, state, zip) values (6, 'Transport', 'Rhode Island', '02905');
insert into BuyBest (storeID, addr, state, zip) values (7, 'Hermina', 'California', '93034');
insert into BuyBest (storeID, addr, state, zip) values (8, 'Arapahoe', 'Nevada', '89105');
insert into BuyBest (storeID, addr, state, zip) values (9, 'Hagan', 'Texas', '75353');
insert into BuyBest (storeID, addr, state, zip) values (10, 'Village', 'Florida', '33448');
insert into BuyBest (storeID, addr, state, zip) values (11, 'Oneill', 'Minnesota', '55590');
insert into BuyBest (storeID, addr, state, zip) values (12, 'Pleasure', 'Florida', '33499');
insert into BuyBest (storeID, addr, state, zip) values (13, 'Kensington', 'Michigan', '48107');
insert into BuyBest (storeID, addr, state, zip) values (14, 'Susan', 'Alabama', '36641');
insert into BuyBest (storeID, addr, state, zip) values (15, 'Buell', 'Pennsylvania', '15205');
insert into BuyBest (storeID, addr, state, zip) values (16, 'Waywood', 'Indiana', '46202');
insert into BuyBest (storeID, addr, state, zip) values (17, 'Main', 'Arizona', '85705');
insert into BuyBest (storeID, addr, state, zip) values (18, 'Starling', 'Nebraska', '68124');
insert into BuyBest (storeID, addr, state, zip) values (19, 'Anderson', 'North Carolina', '27404');
insert into BuyBest (storeID, addr, state, zip) values (20, 'Magdeline', 'Pennsylvania', '15215');
insert into BuyBest (storeID, addr, state, zip) values (21, 'Trailsway', 'Ohio', '44321');
insert into BuyBest (storeID, addr, state, zip) values (22, 'Spaight', 'California', '94132');
insert into BuyBest (storeID, addr, state, zip) values (23, 'Thierer', 'Texas', '75277');
insert into BuyBest (storeID, addr, state, zip) values (24, 'Crest Line', 'Illinois', '62776');
insert into BuyBest (storeID, addr, state, zip) values (25, 'Hanover', 'Nevada', '89595');
insert into BuyBest (storeID, addr, state, zip) values (26, 'Mallard', 'Arizona', '85383');
insert into BuyBest (storeID, addr, state, zip) values (27, 'Sunbrook', 'Oregon', '97221');
insert into BuyBest (storeID, addr, state, zip) values (28, 'Utah', 'California', '93786');
insert into BuyBest (storeID, addr, state, zip) values (29, 'Coolidge', 'North Carolina', '27116');
insert into BuyBest (storeID, addr, state, zip) values (30, 'Burrows', 'Missouri', '63167');
insert into BuyBest (storeID, addr, state, zip) values (31, 'Ludington', 'Ohio', '44760');
insert into BuyBest (storeID, addr, state, zip) values (32, 'Barnett', 'California', '93778');
insert into BuyBest (storeID, addr, state, zip) values (33, 'Utah', 'West Virginia', '25313');
insert into BuyBest (storeID, addr, state, zip) values (34, 'Dovetail', 'California', '95405');
insert into BuyBest (storeID, addr, state, zip) values (35, 'Gerald', 'Minnesota', '55805');
insert into BuyBest (storeID, addr, state, zip) values (36, 'Harbort', 'Pennsylvania', '19196');
insert into BuyBest (storeID, addr, state, zip) values (37, 'Oakridge', 'District of Columbia', '20260');
insert into BuyBest (storeID, addr, state, zip) values (38, 'Golf View', 'Virginia', '22119');
insert into BuyBest (storeID, addr, state, zip) values (39, 'Blackbird', 'North Dakota', '58106');
insert into BuyBest (storeID, addr, state, zip) values (40, 'Express', 'Indiana', '46857');
insert into BuyBest (storeID, addr, state, zip) values (41, 'Onsgard', 'Texas', '79934');
insert into BuyBest (storeID, addr, state, zip) values (42, 'Warbler', 'Indiana', '46015');
insert into BuyBest (storeID, addr, state, zip) values (43, 'Village', 'North Carolina', '27690');
insert into BuyBest (storeID, addr, state, zip) values (44, 'Longview', 'Texas', '76796');
insert into BuyBest (storeID, addr, state, zip) values (45, 'Superior', 'Pennsylvania', '15286');
insert into BuyBest (storeID, addr, state, zip) values (46, '4th', 'Georgia', '30328');
insert into BuyBest (storeID, addr, state, zip) values (47, 'Buena Vista', 'New York', '14609');
insert into BuyBest (storeID, addr, state, zip) values (48, 'Montana', 'Illinois', '60351');
insert into BuyBest (storeID, addr, state, zip) values (49, 'Drewry', 'Nevada', '89714');
insert into BuyBest (storeID, addr, state, zip) values (50, 'Hoepker', 'California', '95298');
insert into BuyBest (storeID, addr, state, zip) values (51, 'Northfield', 'Georgia', '31410');
insert into BuyBest (storeID, addr, state, zip) values (52, 'Park Meadow', 'Texas', '78710');
insert into BuyBest (storeID, addr, state, zip) values (53, 'Bonner', 'Kentucky', '40745');
insert into BuyBest (storeID, addr, state, zip) values (54, 'Ridge Oak', 'Minnesota', '55417');
insert into BuyBest (storeID, addr, state, zip) values (55, 'Vera', 'Idaho', '83705');
insert into BuyBest (storeID, addr, state, zip) values (56, 'South', 'Colorado', '80262');
insert into BuyBest (storeID, addr, state, zip) values (57, 'Charing Cross', 'Texas', '78737');
insert into BuyBest (storeID, addr, state, zip) values (58, 'Vermont', 'Hawaii', '96820');
insert into BuyBest (storeID, addr, state, zip) values (59, 'Mendota', 'Kentucky', '40546');
insert into BuyBest (storeID, addr, state, zip) values (60, 'Clarendon', 'Illinois', '60435');
insert into BuyBest (storeID, addr, state, zip) values (61, 'Dixon', 'Hawaii', '96810');
insert into BuyBest (storeID, addr, state, zip) values (62, 'Sachtjen', 'Texas', '77075');
insert into BuyBest (storeID, addr, state, zip) values (63, 'Continental', 'New York', '11254');
insert into BuyBest (storeID, addr, state, zip) values (64, 'Fulton', 'Arizona', '85099');
insert into BuyBest (storeID, addr, state, zip) values (65, 'Lotheville', 'Florida', '32118');
insert into BuyBest (storeID, addr, state, zip) values (66, 'Crownhardt', 'Pennsylvania', '19160');
insert into BuyBest (storeID, addr, state, zip) values (67, 'Northwestern', 'Kentucky', '40298');
insert into BuyBest (storeID, addr, state, zip) values (68, 'Maryland', 'District of Columbia', '20088');
insert into BuyBest (storeID, addr, state, zip) values (69, 'Arapahoe', 'Florida', '34985');
insert into BuyBest (storeID, addr, state, zip) values (70, 'Clove', 'Oregon', '97286');
insert into BuyBest (storeID, addr, state, zip) values (71, 'Luster', 'Tennessee', '37919');
insert into BuyBest (storeID, addr, state, zip) values (72, 'Morning', 'California', '90045');
insert into BuyBest (storeID, addr, state, zip) values (73, 'La Follette', 'Minnesota', '55123');
insert into BuyBest (storeID, addr, state, zip) values (74, 'Monica', 'Iowa', '50369');
insert into BuyBest (storeID, addr, state, zip) values (75, 'Bowman', 'Texas', '78426');
insert into BuyBest (storeID, addr, state, zip) values (76, 'Gerald', 'Texas', '77388');
insert into BuyBest (storeID, addr, state, zip) values (77, 'Nova', 'Florida', '32595');
insert into BuyBest (storeID, addr, state, zip) values (78, 'Holmberg', 'California', '94286');
insert into BuyBest (storeID, addr, state, zip) values (79, 'Monument', 'Oregon', '97201');
insert into BuyBest (storeID, addr, state, zip) values (80, 'Sullivan', 'California', '94164');
insert into BuyBest (storeID, addr, state, zip) values (81, 'Melrose', 'Texas', '77010');
insert into BuyBest (storeID, addr, state, zip) values (82, 'Express', 'Maryland', '21211');
insert into BuyBest (storeID, addr, state, zip) values (83, 'Carpenter', 'Colorado', '80925');
insert into BuyBest (storeID, addr, state, zip) values (84, 'Dunning', 'West Virginia', '25726');
insert into BuyBest (storeID, addr, state, zip) values (85, 'Continental', 'Florida', '32595');
insert into BuyBest (storeID, addr, state, zip) values (86, 'Heffernan', 'Florida', '34205');
insert into BuyBest (storeID, addr, state, zip) values (87, 'Bartelt', 'California', '94302');
insert into BuyBest (storeID, addr, state, zip) values (88, 'East', 'Connecticut', '06145');
insert into BuyBest (storeID, addr, state, zip) values (89, 'Westend', 'California', '91616');
insert into BuyBest (storeID, addr, state, zip) values (90, 'Jay', 'Michigan', '49018');
insert into BuyBest (storeID, addr, state, zip) values (91, 'Bartillon', 'New York', '12222');
insert into BuyBest (storeID, addr, state, zip) values (92, 'Manufacturers', 'Kentucky', '40215');
insert into BuyBest (storeID, addr, state, zip) values (93, 'Debra', 'Kentucky', '40298');
insert into BuyBest (storeID, addr, state, zip) values (94, '5th', 'Minnesota', '55811');
insert into BuyBest (storeID, addr, state, zip) values (95, 'Eggendart', 'Texas', '76134');
insert into BuyBest (storeID, addr, state, zip) values (96, 'Twin Pines', 'Alabama', '36622');
insert into BuyBest (storeID, addr, state, zip) values (97, 'Golf View', 'New York', '12227');
insert into BuyBest (storeID, addr, state, zip) values (98, 'Dapin', 'Ohio', '45213');
insert into BuyBest (storeID, addr, state, zip) values (99, 'Buell', 'Texas', '76705');
insert into BuyBest (storeID, addr, state, zip) values (100, 'Karstens', 'Florida', '34282');
insert into BuyBest (storeID, addr, state, zip) values (101, 'Fieldstone', 'Oregon', '97271');
insert into BuyBest (storeID, addr, state, zip) values (102, 'Kenwood', 'Texas', '76096');
insert into BuyBest (storeID, addr, state, zip) values (103, 'Clyde Gallagher', 'Colorado', '80930');
insert into BuyBest (storeID, addr, state, zip) values (104, 'Homewood', 'Washington', '98516');
insert into BuyBest (storeID, addr, state, zip) values (105, 'Esch', 'California', '90071');
insert into BuyBest (storeID, addr, state, zip) values (106, 'Grasskamp', 'New York', '10160');
insert into BuyBest (storeID, addr, state, zip) values (107, '4th', 'California', '91186');
insert into BuyBest (storeID, addr, state, zip) values (108, 'Sugar', 'New York', '10705');
insert into BuyBest (storeID, addr, state, zip) values (109, 'Sugar', 'California', '94291');
insert into BuyBest (storeID, addr, state, zip) values (110, 'Scoville', 'Florida', '33673');
insert into BuyBest (storeID, addr, state, zip) values (111, 'Bay', 'Nevada', '89125');
insert into BuyBest (storeID, addr, state, zip) values (112, 'Haas', 'Connecticut', '06510');
insert into BuyBest (storeID, addr, state, zip) values (113, 'Ohio', 'Utah', '84135');
insert into BuyBest (storeID, addr, state, zip) values (114, 'Colorado', 'District of Columbia', '20530');
insert into BuyBest (storeID, addr, state, zip) values (115, 'Nevada', 'Iowa', '51105');
insert into BuyBest (storeID, addr, state, zip) values (116, 'Melody', 'District of Columbia', '20337');
insert into BuyBest (storeID, addr, state, zip) values (117, 'Bluestem', 'Florida', '33142');
insert into BuyBest (storeID, addr, state, zip) values (118, 'Di Loreto', 'Florida', '33320');
insert into BuyBest (storeID, addr, state, zip) values (119, 'Ridge Oak', 'California', '92170');
insert into BuyBest (storeID, addr, state, zip) values (120, 'West', 'Oklahoma', '73190');
insert into BuyBest (storeID, addr, state, zip) values (121, 'Dovetail', 'Virginia', '23220');
insert into BuyBest (storeID, addr, state, zip) values (122, 'Lien', 'Mississippi', '39705');
insert into BuyBest (storeID, addr, state, zip) values (123, 'Burning Wood', 'Kansas', '66642');
insert into BuyBest (storeID, addr, state, zip) values (124, 'Northfield', 'California', '95818');
insert into BuyBest (storeID, addr, state, zip) values (125, 'Warner', 'Georgia', '30311');
insert into BuyBest (storeID, addr, state, zip) values (126, 'High Crossing', 'Florida', '32215');
insert into BuyBest (storeID, addr, state, zip) values (127, 'Charing Cross', 'Massachusetts', '02216');
insert into BuyBest (storeID, addr, state, zip) values (128, 'Barnett', 'Michigan', '48335');
insert into BuyBest (storeID, addr, state, zip) values (129, 'Reindahl', 'Wisconsin', '53285');
insert into BuyBest (storeID, addr, state, zip) values (130, 'Sutteridge', 'Florida', '33315');
insert into BuyBest (storeID, addr, state, zip) values (131, 'Forest Run', 'Texas', '76105');
insert into BuyBest (storeID, addr, state, zip) values (132, 'Delladonna', 'Georgia', '30045');
insert into BuyBest (storeID, addr, state, zip) values (133, 'David', 'Kansas', '67220');
insert into BuyBest (storeID, addr, state, zip) values (134, 'Pleasure', 'Florida', '33315');
insert into BuyBest (storeID, addr, state, zip) values (135, 'Kennedy', 'Texas', '78245');
insert into BuyBest (storeID, addr, state, zip) values (136, 'Monument', 'Texas', '88558');
insert into BuyBest (storeID, addr, state, zip) values (137, 'Erie', 'California', '91616');
insert into BuyBest (storeID, addr, state, zip) values (138, 'Susan', 'Nebraska', '68110');
insert into BuyBest (storeID, addr, state, zip) values (139, 'Nevada', 'Minnesota', '55598');
insert into BuyBest (storeID, addr, state, zip) values (140, 'Farwell', 'California', '93305');
insert into BuyBest (storeID, addr, state, zip) values (141, 'Dawn', 'Texas', '75358');
insert into BuyBest (storeID, addr, state, zip) values (142, 'John Wall', 'Indiana', '46226');
insert into BuyBest (storeID, addr, state, zip) values (143, 'Sutherland', 'Oklahoma', '74116');
insert into BuyBest (storeID, addr, state, zip) values (144, 'Holy Cross', 'California', '90189');
insert into BuyBest (storeID, addr, state, zip) values (145, 'Blue Bill Park', 'Utah', '84130');
insert into BuyBest (storeID, addr, state, zip) values (146, 'Lakewood Gardens', 'Tennessee', '37131');
insert into BuyBest (storeID, addr, state, zip) values (147, 'American', 'California', '94116');
insert into BuyBest (storeID, addr, state, zip) values (148, 'Clove', 'Pennsylvania', '18505');
insert into BuyBest (storeID, addr, state, zip) values (149, 'Eagan', 'New Hampshire', '03804');
insert into BuyBest (storeID, addr, state, zip) values (150, 'Talisman', 'California', '93106');
insert into BuyBest (storeID, addr, state, zip) values (151, 'Monica', 'South Carolina', '29805');
insert into BuyBest (storeID, addr, state, zip) values (152, 'Evergreen', 'Nevada', '89074');
insert into BuyBest (storeID, addr, state, zip) values (153, 'Johnson', 'Florida', '33620');
insert into BuyBest (storeID, addr, state, zip) values (154, 'Ryan', 'Mississippi', '39216');
insert into BuyBest (storeID, addr, state, zip) values (155, 'Oriole', 'Tennessee', '37131');
insert into BuyBest (storeID, addr, state, zip) values (156, 'Bunker Hill', 'District of Columbia', '20010');
insert into BuyBest (storeID, addr, state, zip) values (157, 'Charing Cross', 'Maryland', '21211');
insert into BuyBest (storeID, addr, state, zip) values (158, 'Valley Edge', 'Indiana', '46620');
insert into BuyBest (storeID, addr, state, zip) values (159, 'Menomonie', 'Missouri', '65218');
insert into BuyBest (storeID, addr, state, zip) values (160, 'Hudson', 'Minnesota', '55103');
insert into BuyBest (storeID, addr, state, zip) values (161, 'Roth', 'Oregon', '97271');
insert into BuyBest (storeID, addr, state, zip) values (162, 'Welch', 'California', '90065');
insert into BuyBest (storeID, addr, state, zip) values (163, 'Glacier Hill', 'Missouri', '64101');
insert into BuyBest (storeID, addr, state, zip) values (164, 'Village', 'Louisiana', '70116');
insert into BuyBest (storeID, addr, state, zip) values (165, 'Haas', 'Oklahoma', '73119');
insert into BuyBest (storeID, addr, state, zip) values (166, 'Dixon', 'Pennsylvania', '17140');
insert into BuyBest (storeID, addr, state, zip) values (167, 'Westridge', 'New Mexico', '87505');
insert into BuyBest (storeID, addr, state, zip) values (168, 'Troy', 'Ohio', '44905');
insert into BuyBest (storeID, addr, state, zip) values (169, 'Atwood', 'Tennessee', '38109');
insert into BuyBest (storeID, addr, state, zip) values (170, 'Porter', 'Virginia', '23471');
insert into BuyBest (storeID, addr, state, zip) values (171, 'Stuart', 'New York', '14225');
insert into BuyBest (storeID, addr, state, zip) values (172, 'Starling', 'Virginia', '22184');
insert into BuyBest (storeID, addr, state, zip) values (173, 'Mariners Cove', 'Virginia', '23324');
insert into BuyBest (storeID, addr, state, zip) values (174, 'Acker', 'Illinois', '62705');
insert into BuyBest (storeID, addr, state, zip) values (175, 'School', 'Kentucky', '40233');
insert into BuyBest (storeID, addr, state, zip) values (176, 'Washington', 'Virginia', '24020');
insert into BuyBest (storeID, addr, state, zip) values (177, 'Chive', 'California', '93794');
insert into BuyBest (storeID, addr, state, zip) values (178, 'Atwood', 'New York', '11355');
insert into BuyBest (storeID, addr, state, zip) values (179, 'Londonderry', 'Kentucky', '41905');
insert into BuyBest (storeID, addr, state, zip) values (180, 'Eastwood', 'Georgia', '31605');
insert into BuyBest (storeID, addr, state, zip) values (181, 'Sunnyside', 'Massachusetts', '02405');
insert into BuyBest (storeID, addr, state, zip) values (182, 'Evergreen', 'New York', '13205');
insert into BuyBest (storeID, addr, state, zip) values (183, 'Brickson Park', 'Missouri', '65218');
insert into BuyBest (storeID, addr, state, zip) values (184, 'Drewry', 'Texas', '78044');
insert into BuyBest (storeID, addr, state, zip) values (185, 'Troy', 'Texas', '79977');
insert into BuyBest (storeID, addr, state, zip) values (186, 'Lukken', 'Texas', '78715');
insert into BuyBest (storeID, addr, state, zip) values (187, 'Hooker', 'Georgia', '31205');
insert into BuyBest (storeID, addr, state, zip) values (188, 'Montana', 'Oregon', '97075');
insert into BuyBest (storeID, addr, state, zip) values (189, 'Milwaukee', 'Florida', '34479');
insert into BuyBest (storeID, addr, state, zip) values (190, 'Judy', 'Illinois', '60158');
insert into BuyBest (storeID, addr, state, zip) values (191, 'Butterfield', 'Virginia', '23213');
insert into BuyBest (storeID, addr, state, zip) values (192, 'Fairfield', 'Texas', '88579');
insert into BuyBest (storeID, addr, state, zip) values (193, 'Victoria', 'Louisiana', '70033');
insert into BuyBest (storeID, addr, state, zip) values (194, 'Shopko', 'Texas', '79928');
insert into BuyBest (storeID, addr, state, zip) values (195, 'Burrows', 'Nebraska', '68510');
insert into BuyBest (storeID, addr, state, zip) values (196, 'Sycamore', 'Arizona', '85005');
insert into BuyBest (storeID, addr, state, zip) values (197, 'Pierstorff', 'Florida', '33673');
insert into BuyBest (storeID, addr, state, zip) values (198, 'Gerald', 'Kansas', '66105');
insert into BuyBest (storeID, addr, state, zip) values (199, 'Haas', 'Michigan', '48092');
insert into BuyBest (storeID, addr, state, zip) values (200, 'Pepper Wood', 'California', '90071');
insert into BuyBest (storeID, addr, state, zip) values (201, 'Dovetail', 'Texas', '88589');
insert into BuyBest (storeID, addr, state, zip) values (202, 'Cascade', 'Virginia', '24034');
insert into BuyBest (storeID, addr, state, zip) values (203, 'Village Green', 'California', '93778');
insert into BuyBest (storeID, addr, state, zip) values (204, 'Division', 'California', '92640');
insert into BuyBest (storeID, addr, state, zip) values (205, 'Vidon', 'Florida', '33673');
insert into BuyBest (storeID, addr, state, zip) values (206, 'Shasta', 'California', '92165');
insert into BuyBest (storeID, addr, state, zip) values (207, 'Thompson', 'Wisconsin', '53277');
insert into BuyBest (storeID, addr, state, zip) values (208, 'Texas', 'Texas', '77090');
insert into BuyBest (storeID, addr, state, zip) values (209, 'Lukken', 'Florida', '34135');
insert into BuyBest (storeID, addr, state, zip) values (210, 'Pennsylvania', 'New York', '12262');
insert into BuyBest (storeID, addr, state, zip) values (211, 'Messerschmidt', 'Illinois', '61605');
insert into BuyBest (storeID, addr, state, zip) values (212, 'Clarendon', 'Florida', '33954');
insert into BuyBest (storeID, addr, state, zip) values (213, 'Sunfield', 'West Virginia', '25770');
insert into BuyBest (storeID, addr, state, zip) values (214, 'Hallows', 'Minnesota', '55487');
insert into BuyBest (storeID, addr, state, zip) values (215, 'Welch', 'Nevada', '89145');
insert into BuyBest (storeID, addr, state, zip) values (216, 'Quincy', 'Florida', '33325');
insert into BuyBest (storeID, addr, state, zip) values (217, 'Myrtle', 'Ohio', '43220');
insert into BuyBest (storeID, addr, state, zip) values (218, 'Forster', 'North Carolina', '28205');
insert into BuyBest (storeID, addr, state, zip) values (219, 'Nelson', 'New York', '10557');
insert into BuyBest (storeID, addr, state, zip) values (220, 'Hooker', 'District of Columbia', '20005');
insert into BuyBest (storeID, addr, state, zip) values (221, 'Bunting', 'Ohio', '45254');
insert into BuyBest (storeID, addr, state, zip) values (222, 'Village Green', 'Florida', '33175');
insert into BuyBest (storeID, addr, state, zip) values (223, 'Sunfield', 'District of Columbia', '20099');
insert into BuyBest (storeID, addr, state, zip) values (224, '6th', 'Oklahoma', '74193');
insert into BuyBest (storeID, addr, state, zip) values (225, 'Northwestern', 'West Virginia', '25305');
insert into BuyBest (storeID, addr, state, zip) values (226, 'Fulton', 'Texas', '79968');
insert into BuyBest (storeID, addr, state, zip) values (227, 'Springview', 'Louisiana', '70033');
insert into BuyBest (storeID, addr, state, zip) values (228, 'Anniversary', 'Maryland', '21216');
insert into BuyBest (storeID, addr, state, zip) values (229, 'Loeprich', 'Washington', '99252');
insert into BuyBest (storeID, addr, state, zip) values (230, 'Almo', 'Florida', '33737');
insert into BuyBest (storeID, addr, state, zip) values (231, 'Eastwood', 'Kentucky', '40596');
insert into BuyBest (storeID, addr, state, zip) values (232, 'Farwell', 'New York', '11388');
insert into BuyBest (storeID, addr, state, zip) values (233, 'Ridgeview', 'Colorado', '80209');
insert into BuyBest (storeID, addr, state, zip) values (234, 'Atwood', 'Texas', '77554');
insert into BuyBest (storeID, addr, state, zip) values (235, 'Mitchell', 'New Jersey', '07195');
insert into BuyBest (storeID, addr, state, zip) values (236, 'Walton', 'Ohio', '45243');
insert into BuyBest (storeID, addr, state, zip) values (237, 'Merry', 'Pennsylvania', '15286');
insert into BuyBest (storeID, addr, state, zip) values (238, 'International', 'Pennsylvania', '18105');
insert into BuyBest (storeID, addr, state, zip) values (239, 'Rigney', 'Illinois', '61651');
insert into BuyBest (storeID, addr, state, zip) values (240, 'Marquette', 'California', '95838');
insert into BuyBest (storeID, addr, state, zip) values (241, 'Clarendon', 'Arizona', '85705');
insert into BuyBest (storeID, addr, state, zip) values (242, 'Dunning', 'Maryland', '20719');
insert into BuyBest (storeID, addr, state, zip) values (243, 'Esch', 'Washington', '98008');
insert into BuyBest (storeID, addr, state, zip) values (244, 'Fairfield', 'Texas', '77015');
insert into BuyBest (storeID, addr, state, zip) values (245, 'Sachs', 'Arizona', '85025');
insert into BuyBest (storeID, addr, state, zip) values (246, 'Birchwood', 'Illinois', '60681');
insert into BuyBest (storeID, addr, state, zip) values (247, 'Golden Leaf', 'Pennsylvania', '19141');
insert into BuyBest (storeID, addr, state, zip) values (248, 'Lake View', 'California', '94263');
insert into BuyBest (storeID, addr, state, zip) values (249, 'Mallard', 'Washington', '98405');
insert into BuyBest (storeID, addr, state, zip) values (250, 'Forest Run', 'North Carolina', '28299');
insert into BuyBest (storeID, addr, state, zip) values (251, 'Morningstar', 'Georgia', '30358');
insert into BuyBest (storeID, addr, state, zip) values (252, 'Waubesa', 'Texas', '75358');
insert into BuyBest (storeID, addr, state, zip) values (253, 'Stoughton', 'New York', '14263');
insert into BuyBest (storeID, addr, state, zip) values (254, 'Crownhardt', 'California', '91406');
insert into BuyBest (storeID, addr, state, zip) values (255, 'Hudson', 'Texas', '75241');
insert into BuyBest (storeID, addr, state, zip) values (256, 'East', 'Florida', '34210');
insert into BuyBest (storeID, addr, state, zip) values (257, 'Moose', 'District of Columbia', '20220');
insert into BuyBest (storeID, addr, state, zip) values (258, 'Lake View', 'Illinois', '60505');
insert into BuyBest (storeID, addr, state, zip) values (259, 'Everett', 'Colorado', '80279');
insert into BuyBest (storeID, addr, state, zip) values (260, 'Fuller', 'California', '90101');
insert into BuyBest (storeID, addr, state, zip) values (261, 'Meadow Valley', 'Washington', '98411');
insert into BuyBest (storeID, addr, state, zip) values (262, 'East', 'Florida', '33325');
insert into BuyBest (storeID, addr, state, zip) values (263, 'Crest Line', 'Illinois', '62711');
insert into BuyBest (storeID, addr, state, zip) values (264, 'Crownhardt', 'New York', '10260');
insert into BuyBest (storeID, addr, state, zip) values (265, 'Dawn', 'Pennsylvania', '19495');
insert into BuyBest (storeID, addr, state, zip) values (266, 'Harbort', 'Texas', '79405');
insert into BuyBest (storeID, addr, state, zip) values (267, 'Ramsey', 'Tennessee', '38109');
insert into BuyBest (storeID, addr, state, zip) values (268, 'Ridgeview', 'Texas', '88546');
insert into BuyBest (storeID, addr, state, zip) values (269, 'Morrow', 'Florida', '33330');
insert into BuyBest (storeID, addr, state, zip) values (270, 'Dennis', 'California', '95138');
insert into BuyBest (storeID, addr, state, zip) values (271, 'Southridge', 'Nevada', '89436');
insert into BuyBest (storeID, addr, state, zip) values (272, 'School', 'Florida', '33705');
insert into BuyBest (storeID, addr, state, zip) values (273, 'Di Loreto', 'Colorado', '80940');
insert into BuyBest (storeID, addr, state, zip) values (274, 'Canary', 'Missouri', '64109');
insert into BuyBest (storeID, addr, state, zip) values (275, 'Holy Cross', 'New York', '12255');
insert into BuyBest (storeID, addr, state, zip) values (276, 'Buena Vista', 'Wisconsin', '54313');
insert into BuyBest (storeID, addr, state, zip) values (277, 'Golf Course', 'Texas', '75705');
insert into BuyBest (storeID, addr, state, zip) values (278, 'Anhalt', 'Texas', '77554');
insert into BuyBest (storeID, addr, state, zip) values (279, 'American Ash', 'Florida', '33884');
insert into BuyBest (storeID, addr, state, zip) values (280, 'Bowman', 'Louisiana', '70154');
insert into BuyBest (storeID, addr, state, zip) values (281, 'Di Loreto', 'Kentucky', '40298');
insert into BuyBest (storeID, addr, state, zip) values (282, 'Utah', 'Florida', '32803');
insert into BuyBest (storeID, addr, state, zip) values (283, 'Becker', 'Texas', '79116');
insert into BuyBest (storeID, addr, state, zip) values (284, 'Randy', 'California', '93778');
insert into BuyBest (storeID, addr, state, zip) values (285, 'Arapahoe', 'Arizona', '85305');
insert into BuyBest (storeID, addr, state, zip) values (286, 'Erie', 'New York', '14619');
insert into BuyBest (storeID, addr, state, zip) values (287, 'Bartillon', 'Texas', '77035');
insert into BuyBest (storeID, addr, state, zip) values (288, 'Charing Cross', 'Virginia', '20167');
insert into BuyBest (storeID, addr, state, zip) values (289, 'Oriole', 'Ohio', '43615');
insert into BuyBest (storeID, addr, state, zip) values (290, 'Summer Ridge', 'California', '95354');
insert into BuyBest (storeID, addr, state, zip) values (291, 'Arrowood', 'Virginia', '23509');
insert into BuyBest (storeID, addr, state, zip) values (292, 'Crowley', 'New York', '10090');
insert into BuyBest (storeID, addr, state, zip) values (293, 'Brickson Park', 'Florida', '33963');
insert into BuyBest (storeID, addr, state, zip) values (294, 'Dapin', 'New York', '11355');
insert into BuyBest (storeID, addr, state, zip) values (295, 'Lindbergh', 'Florida', '34479');
insert into BuyBest (storeID, addr, state, zip) values (296, 'Hermina', 'District of Columbia', '20041');
insert into BuyBest (storeID, addr, state, zip) values (297, 'Banding', 'District of Columbia', '20397');
insert into BuyBest (storeID, addr, state, zip) values (298, 'Judy', 'Indiana', '47405');
insert into BuyBest (storeID, addr, state, zip) values (299, 'Becker', 'Tennessee', '38308');
insert into BuyBest (storeID, addr, state, zip) values (300, 'Sachs', 'Georgia', '30045');
insert into BuyBest (storeID, addr, state, zip) values (301, 'Kensington', 'Connecticut', '06721');
insert into BuyBest (storeID, addr, state, zip) values (302, 'Twin Pines', 'New York', '10019');
insert into BuyBest (storeID, addr, state, zip) values (303, 'Talmadge', 'Iowa', '50393');
insert into BuyBest (storeID, addr, state, zip) values (304, 'Buell', 'Indiana', '46814');
insert into BuyBest (storeID, addr, state, zip) values (305, 'Grayhawk', 'Tennessee', '37240');
insert into BuyBest (storeID, addr, state, zip) values (306, 'Fisk', 'California', '92867');
insert into BuyBest (storeID, addr, state, zip) values (307, 'Briar Crest', 'New York', '10249');
insert into BuyBest (storeID, addr, state, zip) values (308, 'Larry', 'Colorado', '80228');
insert into BuyBest (storeID, addr, state, zip) values (309, 'Roth', 'District of Columbia', '20238');
insert into BuyBest (storeID, addr, state, zip) values (310, 'Paget', 'Virginia', '23612');
insert into BuyBest (storeID, addr, state, zip) values (311, 'Ramsey', 'Texas', '78783');
insert into BuyBest (storeID, addr, state, zip) values (312, 'Park Meadow', 'New York', '10305');
insert into BuyBest (storeID, addr, state, zip) values (313, 'Sheridan', 'Nevada', '89110');
insert into BuyBest (storeID, addr, state, zip) values (314, 'Sunfield', 'Virginia', '24009');
insert into BuyBest (storeID, addr, state, zip) values (315, 'Cardinal', 'Indiana', '46825');
insert into BuyBest (storeID, addr, state, zip) values (316, 'Maple Wood', 'Utah', '84115');
insert into BuyBest (storeID, addr, state, zip) values (317, 'Lunder', 'Georgia', '30092');
insert into BuyBest (storeID, addr, state, zip) values (318, 'Montana', 'Kansas', '66606');
insert into BuyBest (storeID, addr, state, zip) values (319, 'Bellgrove', 'Maryland', '21229');
insert into BuyBest (storeID, addr, state, zip) values (320, 'Tomscot', 'Ohio', '43656');
insert into BuyBest (storeID, addr, state, zip) values (321, 'Kennedy', 'Texas', '75062');
insert into BuyBest (storeID, addr, state, zip) values (322, 'Anderson', 'District of Columbia', '20319');
insert into BuyBest (storeID, addr, state, zip) values (323, 'Roxbury', 'Texas', '79928');
insert into BuyBest (storeID, addr, state, zip) values (324, 'Quincy', 'Florida', '33432');
insert into BuyBest (storeID, addr, state, zip) values (325, 'Mccormick', 'Arkansas', '72916');
insert into BuyBest (storeID, addr, state, zip) values (326, 'Logan', 'California', '94116');
insert into BuyBest (storeID, addr, state, zip) values (327, 'Hovde', 'Indiana', '47725');
insert into BuyBest (storeID, addr, state, zip) values (328, 'Grasskamp', 'California', '94616');
insert into BuyBest (storeID, addr, state, zip) values (329, 'Crowley', 'New York', '12255');
insert into BuyBest (storeID, addr, state, zip) values (330, 'Hauk', 'Texas', '75241');
insert into BuyBest (storeID, addr, state, zip) values (331, 'Monument', 'Washington', '98424');
insert into BuyBest (storeID, addr, state, zip) values (332, 'Green', 'Illinois', '60657');
insert into BuyBest (storeID, addr, state, zip) values (333, 'Rockefeller', 'Texas', '76096');
insert into BuyBest (storeID, addr, state, zip) values (334, 'Kedzie', 'Colorado', '80940');
insert into BuyBest (storeID, addr, state, zip) values (335, 'Haas', 'Idaho', '83716');
insert into BuyBest (storeID, addr, state, zip) values (336, 'Shoshone', 'Nebraska', '68179');
insert into BuyBest (storeID, addr, state, zip) values (337, 'Sommers', 'Virginia', '22309');
insert into BuyBest (storeID, addr, state, zip) values (338, 'Express', 'New York', '10110');
insert into BuyBest (storeID, addr, state, zip) values (339, 'Michigan', 'Maryland', '21203');
insert into BuyBest (storeID, addr, state, zip) values (340, 'Grasskamp', 'Texas', '78205');
insert into BuyBest (storeID, addr, state, zip) values (341, 'Stuart', 'Texas', '78415');
insert into BuyBest (storeID, addr, state, zip) values (342, 'Mariners Cove', 'Florida', '32627');
insert into BuyBest (storeID, addr, state, zip) values (343, '6th', 'Nevada', '89706');
insert into BuyBest (storeID, addr, state, zip) values (344, 'Loomis', 'Wisconsin', '53215');
insert into BuyBest (storeID, addr, state, zip) values (345, 'Sunfield', 'Ohio', '43231');
insert into BuyBest (storeID, addr, state, zip) values (346, 'Laurel', 'Arizona', '85053');
insert into BuyBest (storeID, addr, state, zip) values (347, 'Sugar', 'North Carolina', '28205');
insert into BuyBest (storeID, addr, state, zip) values (348, 'Ridgeway', 'California', '93311');
insert into BuyBest (storeID, addr, state, zip) values (349, 'Linden', 'Georgia', '30066');
insert into BuyBest (storeID, addr, state, zip) values (350, 'Pleasure', 'Utah', '84403');
insert into BuyBest (storeID, addr, state, zip) values (351, 'Ridgeview', 'Texas', '78754');
insert into BuyBest (storeID, addr, state, zip) values (352, 'Pennsylvania', 'Indiana', '46216');
insert into BuyBest (storeID, addr, state, zip) values (353, 'Killdeer', 'Georgia', '30392');
insert into BuyBest (storeID, addr, state, zip) values (354, 'Kropf', 'Oklahoma', '73071');
insert into BuyBest (storeID, addr, state, zip) values (355, 'Saint Paul', 'Texas', '88541');
insert into BuyBest (storeID, addr, state, zip) values (356, 'Lillian', 'Maryland', '21203');
insert into BuyBest (storeID, addr, state, zip) values (357, 'Lawn', 'Colorado', '81010');
insert into BuyBest (storeID, addr, state, zip) values (358, 'Barnett', 'Florida', '32819');
insert into BuyBest (storeID, addr, state, zip) values (359, 'Morningstar', 'Colorado', '80915');
insert into BuyBest (storeID, addr, state, zip) values (360, 'Everett', 'Utah', '84189');
insert into BuyBest (storeID, addr, state, zip) values (361, 'Sheridan', 'New York', '10155');
insert into BuyBest (storeID, addr, state, zip) values (362, 'Rigney', 'West Virginia', '25716');
insert into BuyBest (storeID, addr, state, zip) values (363, 'Spohn', 'Maryland', '21211');
insert into BuyBest (storeID, addr, state, zip) values (364, 'Emmet', 'Ohio', '45213');
insert into BuyBest (storeID, addr, state, zip) values (365, 'Elmside', 'Texas', '76115');
insert into BuyBest (storeID, addr, state, zip) values (366, 'Texas', 'Massachusetts', '01610');
insert into BuyBest (storeID, addr, state, zip) values (367, 'Daystar', 'Texas', '77050');
insert into BuyBest (storeID, addr, state, zip) values (368, 'Bayside', 'Indiana', '46857');
insert into BuyBest (storeID, addr, state, zip) values (369, 'Red Cloud', 'Texas', '79116');
insert into BuyBest (storeID, addr, state, zip) values (370, '7th', 'Washington', '98682');
insert into BuyBest (storeID, addr, state, zip) values (371, 'Maple Wood', 'Massachusetts', '02458');
insert into BuyBest (storeID, addr, state, zip) values (372, 'Mitchell', 'New York', '10474');
insert into BuyBest (storeID, addr, state, zip) values (373, 'West', 'Nevada', '89120');
insert into BuyBest (storeID, addr, state, zip) values (374, 'Grayhawk', 'Nebraska', '68164');
insert into BuyBest (storeID, addr, state, zip) values (375, 'Oak', 'Minnesota', '55417');
insert into BuyBest (storeID, addr, state, zip) values (376, 'Eagan', 'Florida', '32803');
insert into BuyBest (storeID, addr, state, zip) values (377, 'Monterey', 'Indiana', '46231');
insert into BuyBest (storeID, addr, state, zip) values (378, 'Lake View', 'California', '92668');
insert into BuyBest (storeID, addr, state, zip) values (379, 'Petterle', 'California', '94142');
insert into BuyBest (storeID, addr, state, zip) values (380, 'Nevada', 'Illinois', '61629');
insert into BuyBest (storeID, addr, state, zip) values (381, 'Banding', 'Missouri', '63169');
insert into BuyBest (storeID, addr, state, zip) values (382, 'Barby', 'Illinois', '60208');
insert into BuyBest (storeID, addr, state, zip) values (383, 'Luster', 'Nevada', '89155');
insert into BuyBest (storeID, addr, state, zip) values (384, 'Crescent Oaks', 'New York', '14614');
insert into BuyBest (storeID, addr, state, zip) values (385, 'Manitowish', 'Texas', '77075');
insert into BuyBest (storeID, addr, state, zip) values (386, 'Holmberg', 'California', '92191');
insert into BuyBest (storeID, addr, state, zip) values (387, 'Lindbergh', 'Oklahoma', '73104');
insert into BuyBest (storeID, addr, state, zip) values (388, 'Bartelt', 'Texas', '78737');
insert into BuyBest (storeID, addr, state, zip) values (389, 'La Follette', 'District of Columbia', '20205');
insert into BuyBest (storeID, addr, state, zip) values (390, 'Vernon', 'North Carolina', '28247');
insert into BuyBest (storeID, addr, state, zip) values (391, 'Anderson', 'Kentucky', '40524');
insert into BuyBest (storeID, addr, state, zip) values (392, 'Sauthoff', 'Tennessee', '37250');
insert into BuyBest (storeID, addr, state, zip) values (393, 'Bluestem', 'New York', '11205');
insert into BuyBest (storeID, addr, state, zip) values (394, 'Springs', 'Florida', '32405');
insert into BuyBest (storeID, addr, state, zip) values (395, 'Hooker', 'West Virginia', '26505');
insert into BuyBest (storeID, addr, state, zip) values (396, 'Brown', 'Texas', '78215');
insert into BuyBest (storeID, addr, state, zip) values (397, 'Moulton', 'Washington', '98442');
insert into BuyBest (storeID, addr, state, zip) values (398, 'Novick', 'Arizona', '85010');
insert into BuyBest (storeID, addr, state, zip) values (399, 'Caliangt', 'New York', '12305');
insert into BuyBest (storeID, addr, state, zip) values (400, 'Oneill', 'Florida', '33972');
insert into BuyBest (storeID, addr, state, zip) values (401, 'Straubel', 'Wisconsin', '53210');
insert into BuyBest (storeID, addr, state, zip) values (402, 'Saint Paul', 'Texas', '77234');
insert into BuyBest (storeID, addr, state, zip) values (403, 'Sommers', 'Texas', '79934');
insert into BuyBest (storeID, addr, state, zip) values (404, 'Park Meadow', 'Ohio', '43226');
insert into BuyBest (storeID, addr, state, zip) values (405, 'Hoepker', 'Kentucky', '40524');
insert into BuyBest (storeID, addr, state, zip) values (406, 'Sage', 'Washington', '99260');
insert into BuyBest (storeID, addr, state, zip) values (407, 'Bayside', 'Georgia', '31132');
insert into BuyBest (storeID, addr, state, zip) values (408, 'Kensington', 'Kentucky', '40618');
insert into BuyBest (storeID, addr, state, zip) values (409, 'Monterey', 'Tennessee', '37245');
insert into BuyBest (storeID, addr, state, zip) values (410, 'Reindahl', 'California', '95833');
insert into BuyBest (storeID, addr, state, zip) values (411, 'Marcy', 'Virginia', '23520');
insert into BuyBest (storeID, addr, state, zip) values (412, 'Schurz', 'California', '92648');
insert into BuyBest (storeID, addr, state, zip) values (413, 'Shelley', 'California', '95128');
insert into BuyBest (storeID, addr, state, zip) values (414, 'Glendale', 'Washington', '98104');
insert into BuyBest (storeID, addr, state, zip) values (415, 'Buena Vista', 'Texas', '79491');
insert into BuyBest (storeID, addr, state, zip) values (416, 'Riverside', 'California', '94089');
insert into BuyBest (storeID, addr, state, zip) values (417, 'Spenser', 'New York', '14652');
insert into BuyBest (storeID, addr, state, zip) values (418, 'Hazelcrest', 'North Carolina', '28410');
insert into BuyBest (storeID, addr, state, zip) values (419, 'Cottonwood', 'Utah', '84189');
insert into BuyBest (storeID, addr, state, zip) values (420, 'Di Loreto', 'California', '93778');
insert into BuyBest (storeID, addr, state, zip) values (421, 'Union', 'Arkansas', '71914');
insert into BuyBest (storeID, addr, state, zip) values (422, 'Dahle', 'Ohio', '43284');
insert into BuyBest (storeID, addr, state, zip) values (423, 'Center', 'Washington', '98115');
insert into BuyBest (storeID, addr, state, zip) values (424, 'Glendale', 'Oregon', '97271');
insert into BuyBest (storeID, addr, state, zip) values (425, 'Miller', 'Pennsylvania', '15274');
insert into BuyBest (storeID, addr, state, zip) values (426, 'Sheridan', 'California', '93709');
insert into BuyBest (storeID, addr, state, zip) values (427, '7th', 'Indiana', '46862');
insert into BuyBest (storeID, addr, state, zip) values (428, 'Scoville', 'Texas', '76711');
insert into BuyBest (storeID, addr, state, zip) values (429, 'Golden Leaf', 'Wisconsin', '54915');
insert into BuyBest (storeID, addr, state, zip) values (430, 'Victoria', 'Florida', '33175');
insert into BuyBest (storeID, addr, state, zip) values (431, 'Di Loreto', 'Missouri', '63180');
insert into BuyBest (storeID, addr, state, zip) values (432, 'Emmet', 'Florida', '32204');
insert into BuyBest (storeID, addr, state, zip) values (433, 'Paget', 'New York', '11254');
insert into BuyBest (storeID, addr, state, zip) values (434, 'Eliot', 'Colorado', '81505');
insert into BuyBest (storeID, addr, state, zip) values (435, 'Kings', 'South Carolina', '29505');
insert into BuyBest (storeID, addr, state, zip) values (436, '7th', 'Michigan', '48076');
insert into BuyBest (storeID, addr, state, zip) values (437, 'Mccormick', 'Colorado', '80299');
insert into BuyBest (storeID, addr, state, zip) values (438, 'Schiller', 'Ohio', '44511');
insert into BuyBest (storeID, addr, state, zip) values (439, 'Scott', 'Tennessee', '38104');
insert into BuyBest (storeID, addr, state, zip) values (440, 'Green Ridge', 'Texas', '78255');
insert into BuyBest (storeID, addr, state, zip) values (441, 'Green Ridge', 'New York', '10019');
insert into BuyBest (storeID, addr, state, zip) values (442, 'Sage', 'District of Columbia', '20046');
insert into BuyBest (storeID, addr, state, zip) values (443, 'Lunder', 'Texas', '78235');
insert into BuyBest (storeID, addr, state, zip) values (444, 'Namekagon', 'Texas', '76115');
insert into BuyBest (storeID, addr, state, zip) values (445, 'Briar Crest', 'California', '91186');
insert into BuyBest (storeID, addr, state, zip) values (446, 'Erie', 'Massachusetts', '02114');
insert into BuyBest (storeID, addr, state, zip) values (447, 'Kensington', 'Pennsylvania', '17605');
insert into BuyBest (storeID, addr, state, zip) values (448, 'Ridgeview', 'Washington', '98042');
insert into BuyBest (storeID, addr, state, zip) values (449, 'Oxford', 'Georgia', '31422');
insert into BuyBest (storeID, addr, state, zip) values (450, 'Knutson', 'Georgia', '31119');
insert into BuyBest (storeID, addr, state, zip) values (451, 'Walton', 'Florida', '33013');
insert into BuyBest (storeID, addr, state, zip) values (452, 'Cordelia', 'Colorado', '81015');
insert into BuyBest (storeID, addr, state, zip) values (453, 'Mallard', 'Minnesota', '55572');
insert into BuyBest (storeID, addr, state, zip) values (454, 'Twin Pines', 'Virginia', '23520');
insert into BuyBest (storeID, addr, state, zip) values (455, 'Jenifer', 'New Mexico', '87140');
insert into BuyBest (storeID, addr, state, zip) values (456, '5th', 'Virginia', '22225');
insert into BuyBest (storeID, addr, state, zip) values (457, 'Havey', 'Texas', '76192');
insert into BuyBest (storeID, addr, state, zip) values (458, 'Daystar', 'Mississippi', '39534');
insert into BuyBest (storeID, addr, state, zip) values (459, 'Kedzie', 'Illinois', '60614');
insert into BuyBest (storeID, addr, state, zip) values (460, 'Northland', 'California', '91505');
insert into BuyBest (storeID, addr, state, zip) values (461, 'Reindahl', 'Florida', '34605');
insert into BuyBest (storeID, addr, state, zip) values (462, 'Springview', 'Illinois', '60663');
insert into BuyBest (storeID, addr, state, zip) values (463, 'Mendota', 'Iowa', '50706');
insert into BuyBest (storeID, addr, state, zip) values (464, 'Anderson', 'New Mexico', '87105');
insert into BuyBest (storeID, addr, state, zip) values (465, 'Lindbergh', 'Missouri', '63131');
insert into BuyBest (storeID, addr, state, zip) values (466, 'Thompson', 'Florida', '33673');
insert into BuyBest (storeID, addr, state, zip) values (467, 'Lotheville', 'Georgia', '31998');
insert into BuyBest (storeID, addr, state, zip) values (468, 'Arrowood', 'New York', '14652');
insert into BuyBest (storeID, addr, state, zip) values (469, 'Weeping Birch', 'New York', '11470');
insert into BuyBest (storeID, addr, state, zip) values (470, 'Nelson', 'Nebraska', '68134');
insert into BuyBest (storeID, addr, state, zip) values (471, 'Erie', 'Ohio', '43615');
insert into BuyBest (storeID, addr, state, zip) values (472, 'Troy', 'Pennsylvania', '15210');
insert into BuyBest (storeID, addr, state, zip) values (473, 'Birchwood', 'Arizona', '86305');
insert into BuyBest (storeID, addr, state, zip) values (474, 'Crownhardt', 'Nevada', '89510');
insert into BuyBest (storeID, addr, state, zip) values (475, 'Ridgeview', 'Alabama', '35244');
insert into BuyBest (storeID, addr, state, zip) values (476, 'Reindahl', 'Delaware', '19810');
insert into BuyBest (storeID, addr, state, zip) values (477, 'Cordelia', 'Texas', '78296');
insert into BuyBest (storeID, addr, state, zip) values (478, 'Crest Line', 'Minnesota', '55573');
insert into BuyBest (storeID, addr, state, zip) values (479, 'Myrtle', 'Tennessee', '37228');
insert into BuyBest (storeID, addr, state, zip) values (480, 'Autumn Leaf', 'Massachusetts', '01105');
insert into BuyBest (storeID, addr, state, zip) values (481, 'International', 'Missouri', '63121');
insert into BuyBest (storeID, addr, state, zip) values (482, 'Walton', 'Ohio', '44111');
insert into BuyBest (storeID, addr, state, zip) values (483, 'Crownhardt', 'California', '92196');
insert into BuyBest (storeID, addr, state, zip) values (484, 'Hollow Ridge', 'Ohio', '44125');
insert into BuyBest (storeID, addr, state, zip) values (485, 'Harbort', 'California', '90055');
insert into BuyBest (storeID, addr, state, zip) values (486, 'Coolidge', 'New York', '12247');
insert into BuyBest (storeID, addr, state, zip) values (487, 'Clarendon', 'Illinois', '60624');
insert into BuyBest (storeID, addr, state, zip) values (488, 'Oak Valley', 'District of Columbia', '20580');
insert into BuyBest (storeID, addr, state, zip) values (489, 'Tony', 'Texas', '77271');
insert into BuyBest (storeID, addr, state, zip) values (490, 'Oak', 'Georgia', '31205');
insert into BuyBest (storeID, addr, state, zip) values (491, 'Gerald', 'Oregon', '97206');
insert into BuyBest (storeID, addr, state, zip) values (492, 'Sheridan', 'Pennsylvania', '19191');
insert into BuyBest (storeID, addr, state, zip) values (493, 'Muir', 'Texas', '88519');
insert into BuyBest (storeID, addr, state, zip) values (494, 'Spenser', 'California', '90060');
insert into BuyBest (storeID, addr, state, zip) values (495, 'Merchant', 'California', '92170');
insert into BuyBest (storeID, addr, state, zip) values (496, 'Algoma', 'Arizona', '85040');
insert into BuyBest (storeID, addr, state, zip) values (497, 'New Castle', 'Tennessee', '38114');
insert into BuyBest (storeID, addr, state, zip) values (498, 'Mallory', 'Maryland', '20709');
insert into BuyBest (storeID, addr, state, zip) values (499, 'Banding', 'Florida', '33777');
insert into BuyBest (storeID, addr, state, zip) values (500, 'Dovetail', 'Indiana', '47306');
insert into BuyBest (storeID, addr, state, zip) values (501, 'Green', 'New York', '12237');
insert into BuyBest (storeID, addr, state, zip) values (502, 'Rigney', 'New York', '14205');
insert into BuyBest (storeID, addr, state, zip) values (503, 'Twin Pines', 'Alabama', '36104');
insert into BuyBest (storeID, addr, state, zip) values (504, 'Harper', 'Texas', '77844');
insert into BuyBest (storeID, addr, state, zip) values (505, 'Killdeer', 'Texas', '77276');
insert into BuyBest (storeID, addr, state, zip) values (506, 'Schlimgen', 'Florida', '33134');
insert into BuyBest (storeID, addr, state, zip) values (507, 'Kings', 'Kansas', '66611');
insert into BuyBest (storeID, addr, state, zip) values (508, 'Moland', 'Iowa', '51110');
insert into BuyBest (storeID, addr, state, zip) values (509, 'Loomis', 'Florida', '33805');
insert into BuyBest (storeID, addr, state, zip) values (510, 'Sunnyside', 'Texas', '76178');
insert into BuyBest (storeID, addr, state, zip) values (511, 'Burning Wood', 'District of Columbia', '20530');
insert into BuyBest (storeID, addr, state, zip) values (512, 'Marquette', 'Louisiana', '70116');
insert into BuyBest (storeID, addr, state, zip) values (513, 'Redwing', 'Michigan', '49544');
insert into BuyBest (storeID, addr, state, zip) values (514, 'Shelley', 'Michigan', '48930');
insert into BuyBest (storeID, addr, state, zip) values (515, 'Oakridge', 'North Carolina', '28263');
insert into BuyBest (storeID, addr, state, zip) values (516, 'Glendale', 'Utah', '84189');
insert into BuyBest (storeID, addr, state, zip) values (517, 'Gina', 'Tennessee', '38197');
insert into BuyBest (storeID, addr, state, zip) values (518, 'Loftsgordon', 'California', '92619');
insert into BuyBest (storeID, addr, state, zip) values (519, 'Cherokee', 'California', '92519');
insert into BuyBest (storeID, addr, state, zip) values (520, 'Westerfield', 'North Carolina', '27690');
insert into BuyBest (storeID, addr, state, zip) values (521, 'Brickson Park', 'Hawaii', '96810');
insert into BuyBest (storeID, addr, state, zip) values (522, 'Delladonna', 'Florida', '32209');
insert into BuyBest (storeID, addr, state, zip) values (523, 'Nevada', 'Colorado', '80925');
insert into BuyBest (storeID, addr, state, zip) values (524, 'Eastwood', 'Washington', '98140');
insert into BuyBest (storeID, addr, state, zip) values (525, 'Sundown', 'Illinois', '60505');
insert into BuyBest (storeID, addr, state, zip) values (526, 'Morrow', 'California', '92030');
insert into BuyBest (storeID, addr, state, zip) values (527, 'Grim', 'New Hampshire', '00214');
insert into BuyBest (storeID, addr, state, zip) values (528, 'Pond', 'Texas', '77025');
insert into BuyBest (storeID, addr, state, zip) values (529, 'Elgar', 'Virginia', '23237');
insert into BuyBest (storeID, addr, state, zip) values (530, 'Chive', 'Colorado', '80249');
insert into BuyBest (storeID, addr, state, zip) values (531, 'Hanover', 'Michigan', '48930');
insert into BuyBest (storeID, addr, state, zip) values (532, 'Vernon', 'Florida', '32230');
insert into BuyBest (storeID, addr, state, zip) values (533, 'Monterey', 'Pennsylvania', '19172');
insert into BuyBest (storeID, addr, state, zip) values (534, 'Daystar', 'Washington', '98042');
insert into BuyBest (storeID, addr, state, zip) values (535, 'Kenwood', 'Oklahoma', '74126');
insert into BuyBest (storeID, addr, state, zip) values (536, 'Russell', 'District of Columbia', '20215');
insert into BuyBest (storeID, addr, state, zip) values (537, 'Wayridge', 'New York', '10260');
insert into BuyBest (storeID, addr, state, zip) values (538, 'Burrows', 'South Carolina', '29505');
insert into BuyBest (storeID, addr, state, zip) values (539, 'Browning', 'New York', '10270');
insert into BuyBest (storeID, addr, state, zip) values (540, 'Gulseth', 'Louisiana', '70005');
insert into BuyBest (storeID, addr, state, zip) values (541, 'Sachs', 'District of Columbia', '20557');
insert into BuyBest (storeID, addr, state, zip) values (542, 'Pierstorff', 'Texas', '79977');
insert into BuyBest (storeID, addr, state, zip) values (543, 'Grim', 'Michigan', '48098');
insert into BuyBest (storeID, addr, state, zip) values (544, 'Westport', 'Colorado', '80015');
insert into BuyBest (storeID, addr, state, zip) values (545, 'Veith', 'Mississippi', '39282');
insert into BuyBest (storeID, addr, state, zip) values (546, 'Chinook', 'Georgia', '30045');
insert into BuyBest (storeID, addr, state, zip) values (547, 'Chinook', 'New York', '11407');
insert into BuyBest (storeID, addr, state, zip) values (548, 'Straubel', 'Colorado', '80915');
insert into BuyBest (storeID, addr, state, zip) values (549, 'Debra', 'Oklahoma', '73173');
insert into BuyBest (storeID, addr, state, zip) values (550, 'Merrick', 'Ohio', '45243');
insert into BuyBest (storeID, addr, state, zip) values (551, 'Anderson', 'Oklahoma', '73071');
insert into BuyBest (storeID, addr, state, zip) values (552, 'Scofield', 'Texas', '76162');
insert into BuyBest (storeID, addr, state, zip) values (553, 'Merry', 'North Carolina', '28215');
insert into BuyBest (storeID, addr, state, zip) values (554, 'Nelson', 'Alabama', '35210');
insert into BuyBest (storeID, addr, state, zip) values (555, 'Almo', 'California', '90810');
insert into BuyBest (storeID, addr, state, zip) values (556, 'Ridgeview', 'Virginia', '23612');
insert into BuyBest (storeID, addr, state, zip) values (557, 'Hanson', 'Alabama', '35215');
insert into BuyBest (storeID, addr, state, zip) values (558, 'Bayside', 'New Jersey', '07188');
insert into BuyBest (storeID, addr, state, zip) values (559, 'Manufacturers', 'Missouri', '63143');
insert into BuyBest (storeID, addr, state, zip) values (560, 'Vernon', 'Washington', '99252');
insert into BuyBest (storeID, addr, state, zip) values (561, 'Badeau', 'Pennsylvania', '15134');
insert into BuyBest (storeID, addr, state, zip) values (562, 'Leroy', 'California', '93794');
insert into BuyBest (storeID, addr, state, zip) values (563, 'Sachtjen', 'California', '91199');
insert into BuyBest (storeID, addr, state, zip) values (564, 'Reindahl', 'Missouri', '64114');
insert into BuyBest (storeID, addr, state, zip) values (565, 'Village', 'Illinois', '62723');
insert into BuyBest (storeID, addr, state, zip) values (566, 'Acker', 'Texas', '77281');
insert into BuyBest (storeID, addr, state, zip) values (567, 'Laurel', 'Pennsylvania', '17605');
insert into BuyBest (storeID, addr, state, zip) values (568, 'Merrick', 'Florida', '32405');
insert into BuyBest (storeID, addr, state, zip) values (569, 'Kennedy', 'Wisconsin', '53726');
insert into BuyBest (storeID, addr, state, zip) values (570, 'Thompson', 'Indiana', '46614');
insert into BuyBest (storeID, addr, state, zip) values (571, 'Thackeray', 'Missouri', '63126');
insert into BuyBest (storeID, addr, state, zip) values (572, 'Stephen', 'Nevada', '89550');
insert into BuyBest (storeID, addr, state, zip) values (573, 'Scofield', 'Pennsylvania', '15134');
insert into BuyBest (storeID, addr, state, zip) values (574, 'Dryden', 'Wisconsin', '53710');
insert into BuyBest (storeID, addr, state, zip) values (575, 'Blackbird', 'West Virginia', '26505');
insert into BuyBest (storeID, addr, state, zip) values (576, 'Clyde Gallagher', 'Missouri', '63180');
insert into BuyBest (storeID, addr, state, zip) values (577, 'Corscot', 'Florida', '33034');
insert into BuyBest (storeID, addr, state, zip) values (578, 'Manley', 'Nevada', '89595');
insert into BuyBest (storeID, addr, state, zip) values (579, 'Park Meadow', 'Ohio', '45254');
insert into BuyBest (storeID, addr, state, zip) values (580, 'La Follette', 'Minnesota', '55123');
insert into BuyBest (storeID, addr, state, zip) values (581, 'Old Gate', 'California', '90847');
insert into BuyBest (storeID, addr, state, zip) values (582, 'Warrior', 'District of Columbia', '20088');
insert into BuyBest (storeID, addr, state, zip) values (583, 'Pennsylvania', 'Nevada', '89150');
insert into BuyBest (storeID, addr, state, zip) values (584, 'Cody', 'Wisconsin', '54305');
insert into BuyBest (storeID, addr, state, zip) values (585, 'Novick', 'Nevada', '89115');
insert into BuyBest (storeID, addr, state, zip) values (586, 'Walton', 'New Jersey', '07544');
insert into BuyBest (storeID, addr, state, zip) values (587, 'Laurel', 'Nebraska', '68110');
insert into BuyBest (storeID, addr, state, zip) values (588, 'Blaine', 'Kentucky', '40266');
insert into BuyBest (storeID, addr, state, zip) values (589, 'Vernon', 'Georgia', '30061');
insert into BuyBest (storeID, addr, state, zip) values (590, 'Sachtjen', 'Minnesota', '55572');
insert into BuyBest (storeID, addr, state, zip) values (591, 'Scoville', 'Florida', '33994');
insert into BuyBest (storeID, addr, state, zip) values (592, 'Farmco', 'New York', '10045');
insert into BuyBest (storeID, addr, state, zip) values (593, 'Armistice', 'New York', '14639');
insert into BuyBest (storeID, addr, state, zip) values (594, 'Mockingbird', 'Connecticut', '06152');
insert into BuyBest (storeID, addr, state, zip) values (595, 'Talmadge', 'Virginia', '22205');
insert into BuyBest (storeID, addr, state, zip) values (596, 'Calypso', 'California', '95150');
insert into BuyBest (storeID, addr, state, zip) values (597, '7th', 'Oregon', '97216');
insert into BuyBest (storeID, addr, state, zip) values (598, 'Linden', 'Tennessee', '38131');
insert into BuyBest (storeID, addr, state, zip) values (599, 'Vidon', 'Iowa', '50305');
insert into BuyBest (storeID, addr, state, zip) values (600, 'Little Fleur', 'Utah', '84093');
insert into BuyBest (storeID, addr, state, zip) values (601, 'Clemons', 'California', '92191');
insert into BuyBest (storeID, addr, state, zip) values (602, 'Shasta', 'Washington', '98516');
insert into BuyBest (storeID, addr, state, zip) values (603, 'Delladonna', 'South Carolina', '29203');
insert into BuyBest (storeID, addr, state, zip) values (604, 'Leroy', 'Florida', '33605');
insert into BuyBest (storeID, addr, state, zip) values (605, 'Vidon', 'Nevada', '89105');
insert into BuyBest (storeID, addr, state, zip) values (606, 'Lukken', 'Arizona', '85062');
insert into BuyBest (storeID, addr, state, zip) values (607, 'Clemons', 'Pennsylvania', '17622');
insert into BuyBest (storeID, addr, state, zip) values (608, 'Jana', 'Florida', '34479');
insert into BuyBest (storeID, addr, state, zip) values (609, 'Main', 'California', '93907');
insert into BuyBest (storeID, addr, state, zip) values (610, 'Golden Leaf', 'Florida', '33694');
insert into BuyBest (storeID, addr, state, zip) values (611, 'Golden Leaf', 'Connecticut', '06859');
insert into BuyBest (storeID, addr, state, zip) values (612, 'Prairieview', 'California', '92662');
insert into BuyBest (storeID, addr, state, zip) values (613, 'Blackbird', 'Idaho', '83716');
insert into BuyBest (storeID, addr, state, zip) values (614, 'Shoshone', 'Pennsylvania', '19093');
insert into BuyBest (storeID, addr, state, zip) values (615, 'Heffernan', 'California', '92410');
insert into BuyBest (storeID, addr, state, zip) values (616, 'Moulton', 'California', '94273');
insert into BuyBest (storeID, addr, state, zip) values (617, 'American', 'Minnesota', '55572');
insert into BuyBest (storeID, addr, state, zip) values (618, 'Riverside', 'Texas', '88530');
insert into BuyBest (storeID, addr, state, zip) values (619, 'Waxwing', 'Washington', '98121');
insert into BuyBest (storeID, addr, state, zip) values (620, 'Mcbride', 'Missouri', '63150');
insert into BuyBest (storeID, addr, state, zip) values (621, 'Summit', 'Florida', '32885');
insert into BuyBest (storeID, addr, state, zip) values (622, 'Spenser', 'Texas', '78732');
insert into BuyBest (storeID, addr, state, zip) values (623, 'Huxley', 'Florida', '34479');
insert into BuyBest (storeID, addr, state, zip) values (624, 'Burrows', 'Oregon', '97306');
insert into BuyBest (storeID, addr, state, zip) values (625, 'Hovde', 'Wisconsin', '53277');
insert into BuyBest (storeID, addr, state, zip) values (626, 'Rutledge', 'Virginia', '24515');
insert into BuyBest (storeID, addr, state, zip) values (627, 'Arkansas', 'Georgia', '30386');
insert into BuyBest (storeID, addr, state, zip) values (628, 'Sachs', 'New York', '11024');
insert into BuyBest (storeID, addr, state, zip) values (629, 'Texas', 'Colorado', '80638');
insert into BuyBest (storeID, addr, state, zip) values (630, 'East', 'Colorado', '80525');
insert into BuyBest (storeID, addr, state, zip) values (631, 'Valley Edge', 'Connecticut', '06673');
insert into BuyBest (storeID, addr, state, zip) values (632, 'Judy', 'Florida', '32123');
insert into BuyBest (storeID, addr, state, zip) values (633, '2nd', 'Florida', '33028');
insert into BuyBest (storeID, addr, state, zip) values (634, 'Burning Wood', 'Colorado', '80920');
insert into BuyBest (storeID, addr, state, zip) values (635, 'Luster', 'California', '94154');
insert into BuyBest (storeID, addr, state, zip) values (636, 'Stuart', 'Alaska', '99517');
insert into BuyBest (storeID, addr, state, zip) values (637, 'Sutherland', 'California', '92612');
insert into BuyBest (storeID, addr, state, zip) values (638, 'Derek', 'Missouri', '64101');
insert into BuyBest (storeID, addr, state, zip) values (639, 'Maryland', 'Illinois', '60669');
insert into BuyBest (storeID, addr, state, zip) values (640, 'Bayside', 'North Carolina', '27621');
insert into BuyBest (storeID, addr, state, zip) values (641, 'Washington', 'Connecticut', '06825');
insert into BuyBest (storeID, addr, state, zip) values (642, 'Forest Run', 'District of Columbia', '20409');
insert into BuyBest (storeID, addr, state, zip) values (643, 'Onsgard', 'Connecticut', '06160');
insert into BuyBest (storeID, addr, state, zip) values (644, 'Kropf', 'Florida', '33153');
insert into BuyBest (storeID, addr, state, zip) values (645, 'Graceland', 'Louisiana', '71151');
insert into BuyBest (storeID, addr, state, zip) values (646, 'Melby', 'Florida', '34620');
insert into BuyBest (storeID, addr, state, zip) values (647, 'Nova', 'Massachusetts', '02298');
insert into BuyBest (storeID, addr, state, zip) values (648, 'Westerfield', 'Wyoming', '82007');
insert into BuyBest (storeID, addr, state, zip) values (649, 'Northfield', 'Florida', '33147');
insert into BuyBest (storeID, addr, state, zip) values (650, 'Hintze', 'Nebraska', '68110');
insert into BuyBest (storeID, addr, state, zip) values (651, 'Toban', 'Texas', '79159');
insert into BuyBest (storeID, addr, state, zip) values (652, 'Loomis', 'California', '93311');
insert into BuyBest (storeID, addr, state, zip) values (653, 'Sommers', 'District of Columbia', '20310');
insert into BuyBest (storeID, addr, state, zip) values (654, 'Tennessee', 'Pennsylvania', '15210');
insert into BuyBest (storeID, addr, state, zip) values (655, 'Lake View', 'Hawaii', '96845');
insert into BuyBest (storeID, addr, state, zip) values (656, 'Vernon', 'California', '95210');
insert into BuyBest (storeID, addr, state, zip) values (657, 'Corben', 'Texas', '78410');
insert into BuyBest (storeID, addr, state, zip) values (658, 'Pepper Wood', 'Ohio', '43231');
insert into BuyBest (storeID, addr, state, zip) values (659, 'Bobwhite', 'Wisconsin', '54915');
insert into BuyBest (storeID, addr, state, zip) values (660, 'Norway Maple', 'Arkansas', '72231');
insert into BuyBest (storeID, addr, state, zip) values (661, 'Butternut', 'South Dakota', '57198');
insert into BuyBest (storeID, addr, state, zip) values (662, 'Hintze', 'California', '93773');
insert into BuyBest (storeID, addr, state, zip) values (663, 'Del Sol', 'Florida', '34210');
insert into BuyBest (storeID, addr, state, zip) values (664, 'Roxbury', 'Florida', '32825');
insert into BuyBest (storeID, addr, state, zip) values (665, 'Jay', 'California', '93750');
insert into BuyBest (storeID, addr, state, zip) values (666, 'Myrtle', 'North Carolina', '27150');
insert into BuyBest (storeID, addr, state, zip) values (667, 'Randy', 'California', '95128');
insert into BuyBest (storeID, addr, state, zip) values (668, 'Meadow Vale', 'Missouri', '64199');
insert into BuyBest (storeID, addr, state, zip) values (669, 'Chinook', 'Texas', '79491');
insert into BuyBest (storeID, addr, state, zip) values (670, 'Clove', 'Colorado', '80223');
insert into BuyBest (storeID, addr, state, zip) values (671, 'Michigan', 'South Carolina', '29805');
insert into BuyBest (storeID, addr, state, zip) values (672, 'Merry', 'New Jersey', '07195');
insert into BuyBest (storeID, addr, state, zip) values (673, 'Waubesa', 'District of Columbia', '20535');
insert into BuyBest (storeID, addr, state, zip) values (674, 'Muir', 'Minnesota', '55565');
insert into BuyBest (storeID, addr, state, zip) values (675, 'Jana', 'Texas', '75710');
insert into BuyBest (storeID, addr, state, zip) values (676, 'Esch', 'Texas', '75397');
insert into BuyBest (storeID, addr, state, zip) values (677, 'Ridgeview', 'California', '92805');
insert into BuyBest (storeID, addr, state, zip) values (678, 'Service', 'District of Columbia', '20442');
insert into BuyBest (storeID, addr, state, zip) values (679, 'Emmet', 'Pennsylvania', '15274');
insert into BuyBest (storeID, addr, state, zip) values (680, 'Manitowish', 'Pennsylvania', '17622');
insert into BuyBest (storeID, addr, state, zip) values (681, 'Armistice', 'New Mexico', '87105');
insert into BuyBest (storeID, addr, state, zip) values (682, 'Jana', 'Virginia', '23289');
insert into BuyBest (storeID, addr, state, zip) values (683, 'Bonner', 'Texas', '76544');
insert into BuyBest (storeID, addr, state, zip) values (684, 'Vahlen', 'California', '90805');
insert into BuyBest (storeID, addr, state, zip) values (685, 'Lakewood', 'Massachusetts', '02163');
insert into BuyBest (storeID, addr, state, zip) values (686, 'Carberry', 'Pennsylvania', '15266');
insert into BuyBest (storeID, addr, state, zip) values (687, 'Drewry', 'Texas', '79955');
insert into BuyBest (storeID, addr, state, zip) values (688, 'Butternut', 'Georgia', '30351');
insert into BuyBest (storeID, addr, state, zip) values (689, 'Kennedy', 'Washington', '99210');
insert into BuyBest (storeID, addr, state, zip) values (690, 'Eagle Crest', 'New Mexico', '87592');
insert into BuyBest (storeID, addr, state, zip) values (691, 'New Castle', 'Arizona', '85743');
insert into BuyBest (storeID, addr, state, zip) values (692, 'Swallow', 'Virginia', '23324');
